
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21how to 
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install --file pom.xml
      
    - name: login to docker registry
      uses: docker/login-action@v3
      with:
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}

    - name: Build and push
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKER_PASSWORD }}
      run: |
          docker build -t <DOCKERHUB_USERNAME>/my-app:latest .
          docker push <DOCKERHUB_USERNAME>/my-app:latest
