
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21how to 
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install --file pom.xml
      
    - name: login to docker registry
      uses: docker/login-action@v3
      with:
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}

    - name: Build and push
      env:
        DOCKERHUB_USERNAME: ${{ secrets.USERNAME }}
      run: |
          docker build -t $DOCKERHUB_USERNAME/danushka95/danu-repo/app:latest .
          docker push $DOCKERHUB_USERNAME/danushka95/danu-repo/app:latest
          
